// 1. Find

	SASH_COMBINE_GRADE_1 = 80,
	SASH_COMBINE_GRADE_2 = 70,
	SASH_COMBINE_GRADE_3 = 50,
	SASH_COMBINE_GRADE_4 = 30,
	
// 2. Change with

#ifdef __SASH_SYSTEM_EXTENDED__
	SASH_COMBINE_GRADE_1 = 100,
	SASH_COMBINE_GRADE_2 = 100,
	SASH_COMBINE_GRADE_3 = 100,
	SASH_COMBINE_GRADE_4 = 30,
#else
	SASH_COMBINE_GRADE_1 = 80,
	SASH_COMBINE_GRADE_2 = 70,
	SASH_COMBINE_GRADE_3 = 50,
	SASH_COMBINE_GRADE_4 = 30,
#endif